baseURL = "https://briantward.github.io/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
paginate = 20
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "Everyday Linux"
[author]
  gravatarEmail = "bward@redhat.com"
  homepageText = "Everyday Linux"
  name = "Everyday Linux"
[params]
  description = "Examples of working solutions in everyday Linux."
  disqusShortname = "test"
  googleAnalytics = ""
  licence = "[Some Rights Reserved](http://creativecommons.org/licenses/by-sa/4.0/)."
  adsenseDataAdClient = ""
  adsenseDataAdSlot = ""
  addThisId = ""
[permalinks]
  posts = "/:slug/"
[pygmentsOptions]
  linenos = false
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Publications"
  weight = -90
  identifier = "publications"
  url = "/publications/"
[[menu.pages]]
  name = "Photos"
  weight = -80
  identifier = "photos"
  url = "/photos/"
