---
title: oc Tips
date: 2021-01-10
categories: ["tips"]
tags: ["oc"]
language: en
slug: oc-tips
---

== OC Command Tips

 $ oc login -u system:admin

 $ oc whoami --config=$HOME/.kube/config
 
Show all resources... and I mean ALL:

 $ kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n openshift-monitoring

Show docker images on node for each node found in pods listing. (Thanks Todd Penn)

 $ for node in $(oc get pods -o jsonpath='{range .items[*].spec}{.nodeName}{" "}{end}'); do echo $node; ssh $node "docker images";done

Capture total CPU usage in cluster:

 $ oc describe nodes | grep -P "cpu:\s*\d$" | awk '{s+=$2} END {print s}'

Find AMI Id on AWS MachineSet:

 $ oc --context ${context} get machineset -n openshift-machine-api -o jsonpath='{.items[0].spec.template.spec.providerSpec.value.ami.id}

Find ClusterID from Install:

 $ cat .openshift_install_state.json | jq -r '."*installconfig.ClusterID".InfraID'
 $ jq -r .infraID metadata.json

The default IngressController object definition doesn't acknowledge Cloud defaults created at install (e.g. privateVPN). So if you delete the default IngressController and it gets recreated, it will not know this.

 $ oc get ingresscontroller default -n openshift-ingress-operator -o jsonpath="{.status.ingress[*].conditions[?(@.type=='Admitted')].status}"

Move static pods to temp to shut them down (from CoreOS node):

 # sudo mv /etc/kubernetes/manifests/kube-apiserver-pod.yaml /tmp
