---
title: Lenovo BIOS/UEFI update via USB from Linux
date: 2018-05-19
categories: ["linux"]
tags: ["linux","bios","uefi","update","USB"]
language: en
slug: lenovo-linux-bios-update 
---

= Lenovo BIOS/UEFI update via USB from Linux

I'm on a Lenovo T460s running fedora 27.  One day, I ran into an issue with
my video setup. It occurred to me that I had not updated my bios in a while,
and since the whole Meltdown/Spectre thing came up, I should probably check on 
this.  Yes, sure enough, I was on patch 1.20, the latest was 1.34, and the fix
for Meltdown/Spectre was in 1.31.  Good thing no one cares about my machine 
but me.

. Find your system's bios update from Lenovo, via Bootable CD.  Mine, a T460s,
was here: https://pcsupport.lenovo.com/us/en/downloads/ds112118

. Check out this guys's great post. You would think you could just copy the
`.iso` to your USB device with `dd`, but no you cannot.  It's a CD format `.iso`
and you have to pull out the CD formatting with this nice utility called 
`geteltorito`.

https://workaround.org/article/updating-the-bios-on-lenovo-laptops-from-linux-using-a-USB-flash-stick/

 # wget https://download.lenovo.com/pccbbs/mobiles/n1cur21w.iso
 # dnf install geteltorito
 # geteltorito -o bios.img n1cur21w.iso

Make sure you identify the correct block device of your USB drive or you will
probably have lots of other problems. This command might be helpful.

 # dmesg | grep sd

My block device for my USB stick is `/dev/sdb`.  So here is the dd command to
copy the image to the USB:

 # dd if=bios.img of=/dev/sdb
